options:
  cuda-version:
    type: string
    default: "8.0.61"
    description: |
      The version of CUDA to be installed.
  cuda-subversion:
    type: string
    default: "1"
    description: |
      The subversion of CUDA to be installed.
